# カフェ売上モックデータ生成設定 (RDB対応版)

# データベース設定
database:
  # 開発・本番環境での切り替え
  default_engine: "sqlite" # sqlite, postgresql, mysql
  connections:
    sqlite:
      path: "data/cafe_mock_sales.db"
    postgresql:
      host: "localhost"
      port: 5432
      database: "cafe_mock_sales"
      # 実際の接続情報は環境変数から取得
    mysql:
      host: "localhost"
      port: 3306
      database: "cafe_mock_sales"

# 出力設定 (複数形式対応)
output:
  formats: ["csv", "json", "xlsx", "db"] # 出力したい形式を指定
  encoding: "utf-8"
  file_paths:
    csv_dir: "data/csv/"
    json_dir: "data/json/"
    xlsx_dir: "data/xlsx/"
  # テーブル設計に対応したファイル分割
  table_structure:
    customers: true # 顧客テーブル
    orders: true # 注文テーブル
    order_items: true # 注文詳細テーブル
    menu_items: true # メニューテーブル
    daily_summary: true # 日時集計テーブル

# データ生成設定
data_generation:
  # データ生成期間
  start_date: "2023-01-01"
  end_date: "2024-12-31"

  # 正規化に対応したID生成設定
  id_generation:
    customer_id_start: 1000
    order_id_start: 10000
    menu_id_start: 100

  # 営業時間
  business_hours:
    open: 9
    close: 18
    closed_days: [3] # 木曜定休日

  # トラフィック設定
  base_customers_per_hour: 8 # 1時間あたりの平均来客数

  # 曜日別係数 (月曜=0, 日曜=6)
  0: 0.8 # 月曜
  1: 0.9 # 火曜
  2: 1.0 # 水曜
  3: 0.0 # 木曜は定休日
  4: 1.0 # 金曜
  5: 1.2 # 土曜
  6: 1.3 # 日曜

  # 時間帯別係数
  hour_multiplier:
    9: 0.7 # 朝
    10: 1.0
    11: 1.2
    12: 1.5 # ランチピーク
    13: 1.4
    14: 1.1
    15: 1.3 # カフェタイム
    16: 1.2
    17: 0.9 # 夕方

  # 天気による影響
  weather_multiplier:
    sunny: 1.2
    cloudy: 1.0
    rainy: 0.7
    snowy: 0.5

  # 月別季節による影響
  seasonal_multiplier:
    1: 0.8 # 1月
    2: 0.9 # 2月
    3: 1.1 # 3月
    4: 1.2 # 4月
    5: 1.1 # 5月
    6: 1.0 # 6月
    7: 1.3 # 7月(夏休み)
    8: 1.3 # 8月(夏休み)
    9: 1.1 # 9月
    10: 1.2 # 10月
    11: 1.0 # 11月
    12: 1.3 # 12月(年末)

  # 特別イベントを設定
  special_events:
    - date: "2023-12-24"
      multiplier: 1.5 # クリスマス
    - date: "2023-02-14"
      multiplier: 1.3 # バレンタインデー
    - date: "2023-04-23"
      multiplier: 1.7 # 創業記念日

# 正規化に対応したメニュー設定
menu:
  categories:
    - id: 1
      name: "モーニング"
      description: "朝のセットメニュー"
    - id: 2
      name: "ランチ"
      description: "昼のセットメニュー"
    - id: 3
      name: "軽食"
      description: "軽い食事"
    - id: 4
      name: "ドリンク"
      description: "飲み物"
    - id: 1
      name: "スイーツ"
      description: "デザート・甘味"

  items:
    # モーニングセット
    - id: 101
      name: "モーニングA"
      category_id: 1
      price: 600
      cost: 250
      available_hours: [9, 10, 11]
      popularity_weight: 0.3
      is_seasonal: false

    - id: 102
      name: "モーニングB"
      category_id: 1
      price: 700
      cost: 280
      available_hours: [9, 10, 11]
      popularity_weight: 0.25
      is_seasonal: false

    - id: 103
      name: "モーニングC"
      category_id: 1
      price: 600
      cost: 250
      available_hours: [9, 10, 11]
      popularity_weight: 0.2
      is_seasonal: false

    - id: 104
      name: "モーニングD"
      category_id: 1
      price: 650
      cost: 270
      available_hours: [9, 10, 11]
      popularity_weight: 0.25
      is_seasonal: false

    # ランチセット
    - id: 201
      name: "ランチA"
      category_id: 2
      price: 900
      cost: 400
      available_hours: [11, 12, 13, 14]
      popularity_weight: 0.35
      is_seasonal: false

    - id: 202
      name: "ランチB"
      category_id: 2
      price: 950
      cost: 420
      available_hours: [11, 12, 13, 14]
      popularity_weight: 0.35
      is_seasonal: false

    - id: 203
      name: "ランチB"
      category_id: 2
      price: 950
      cost: 430
      available_hours: [11, 12, 13, 14]
      popularity_weight: 0.3
      is_seasonal: false

    # 軽食

    - id: 301
      name: "ナポリタン"
      category_id: 3
      price: 850
      cost: 320
      available_hours: [11, 12, 13, 14, 15, 16]
      popularity_weight: 0.2
      is_seasonal: false

    - id: 302
      name: "ミートソース"
      category_id: 3
      price: 850
      cost: 340
      available_hours: [11, 12, 13, 14, 15, 16]
      popularity_weight: 0.22
      is_seasonal: false

    - id: 303
      name: "カルボナーラ"
      category_id: 3
      price: 850
      cost: 360
      available_hours: [11, 12, 13, 14, 15, 16]
      popularity_weight: 0.18
      is_seasonal: false

    - id: 304
      name: "焼きそば"
      category_id: 3
      price: 750
      cost: 280
      available_hours: [11, 12, 13, 14, 15, 16]
      popularity_weight: 0.15
      is_seasonal: false

    - id: 305
      name: "カレーライス"
      category_id: 3
      price: 750
      cost: 300
      available_hours: [11, 12, 13, 14, 15, 16]
      popularity_weight: 0.25
      is_seasonal: false

    # ドリンク
    - id: 401
      name: "ホットコーヒー"
      category_id: 4
      price: 400
      cost: 80
      available_hours: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
      popularity_weight: 0.4
      is_seasonal: true
      seasonal_preference: "winter"
      seasonal_multiplier: 1.3

    - id: 402
      name: "アイスコーヒー"
      category_id: 4
      price: 400
      cost: 90
      available_hours: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
      popularity_weight: 0.3
      is_seasonal: true
      seasonal_preference: "summer"
      seasonal_multiplier: 1.5

    - id: 403
      name: "ホットティー"
      category_id: 4
      price: 400
      cost: 70
      available_hours: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
      popularity_weight: 0.15
      is_seasonal: true
      seasonal_preference: "winter"
      seasonal_multiplier: 1.2

    - id: 404
      name: "アイスティー"
      category_id: 4
      price: 400
      cost: 80
      available_hours: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
      popularity_weight: 0.15
      is_seasonal: true
      seasonal_preference: "summer"
      seasonal_multiplier: 1.4

    # スイーツ
    - id: 501
      name: "ケーキセット"
      category_id: 5
      price: 700
      cost: 280
      available_hours: [13, 14, 15, 16, 17]
      popularity_weight: 0.4
      is_seasonal: false

    - id: 502
      name: "2色アイス"
      category_id: 5
      price: 400
      cost: 120
      available_hours: [13, 14, 15, 16, 17]
      popularity_weight: 0.3
      is_seasonal: true
      seasonal_preference: "summer"
      seasonal_multiplier: 2.0

    - id: 503
      name: "プリン・アラモード"
      category_id: 5
      price: 800
      cost: 300
      available_hours: [13, 14, 15, 16, 17]
      popularity_weight: 0.3
      is_seasonal: false

# 顧客設定 (正規化対応)
customers:
  # 年齢層マスター
  age_groups:
    - id: 1
      name: "teens"
      min_age: 13
      max_age: 19
      base_ratio: 0.15
    - id: 2
      name: "twenties"
      min_age: 20
      max_age: 29
      base_ratio: 0.35
    - id: 3
      name: "thirties"
      min_age: 30
      max_age: 39
      base_ratio: 0.25
    - id: 4
      name: "forties"
      min_age: 40
      max_age: 49
      base_ratio: 0.15
    - id: 5
      name: "seniors"
      min_age: 50
      max_age: 80
      base_ratio: 0.10

  # 基本性別分布
  gender_distribution:
    male: 0.45
    female: 0.55

  # 時間帯・曜日パターン
  behavioral_patterns:
    - pattern_id: 1
      name: "平日モーニング"
      conditions:
        day_types: ["weekday"]
        hours: [9, 10, 11]
      demographics:
        gender_ratio:
          male: 0.70
          female: 0.30
        age_distribution:
          teens: 0.05
          twenties: 0.25
          thirties: 0.40
          forties: 0.25
          seniors: 0.05

    - pattern_id: 2
      name: "平日ランチ"
      conditions:
        day_types: ["weekday"]
        hours: [12, 13, 14]
      demographics:
        gender_ratio:
          male: 0.55
          female: 0.45
        age_distribution:
          teens: 0.05
          twenties: 0.35
          thirties: 0.35
          forties: 0.20
          seniors: 0.05

    - pattern_id: 3
      name: "平日ティータイム"
      conditions:
        day_types: ["weekday"]
        hours: [15, 16, 17]
      demographics:
        gender_ratio:
          male: 0.25
          female: 0.75
        age_distribution:
          teens: 0.20
          twenties: 0.45
          thirties: 0.25
          forties: 0.10
          seniors: 0.00

    - pattern_id: 4
      name: "休日全時間帯"
      conditions:
        day_types: ["weekend"]
        hours: [9, 10, 11, 12, 13, 14, 15, 16, 17]
      demographics:
        gender_ratio:
          male: 0.45
          female: 0.55
        age_distribution:
          teens: 0.20
          twenties: 0.30
          thirties: 0.25
          forties: 0.15
          seniors: 0.10

  # 顧客セグメント別嗜好
  preferences:
    male:
      teens:
        モーニング: 1.0
        ランチ: 1.0
        軽食: 1.3
        ドリンク: 1.3
        スイーツ: 0.7
      twenties:
        モーニング: 1.2
        ランチ: 1.3
        軽食: 1.1
        ドリンク: 1.0
        スイーツ: 0.5
      thirties:
        モーニング: 1.4
        ランチ: 1.2
        軽食: 1.0
        ドリンク: 1.1
        スイーツ: 0.7
      forties:
        モーニング: 1.3
        ランチ: 1.1
        軽食: 0.9
        ドリンク: 1.2
        スイーツ: 0.8
      seniors:
        モーニング: 1.1
        ランチ: 1.0
        軽食: 0.8
        ドリンク: 1.3
        スイーツ: 0.9
    female:
      teens:
        モーニング: 0.8
        ランチ: 1.0
        軽食: 1.1
        ドリンク: 1.2
        スイーツ: 1.6
      twenties:
        モーニング: 0.9
        ランチ: 1.1
        軽食: 1.0
        ドリンク: 1.3
        スイーツ: 1.5
      thirties:
        モーニング: 1.0
        ランチ: 1.0
        軽食: 0.9
        ドリンク: 1.2
        スイーツ: 1.3
      forties:
        モーニング: 1.3
        ランチ: 1.1
        軽食: 0.9
        ドリンク: 1.2
        スイーツ: 0.8
      seniors:
        モーニング: 1.0
        ランチ: 0.8
        軽食: 0.7
        ドリンク: 1.4
        スイーツ: 1.1

# データ品質設定(学習用に意図的にノイズを発生させる)
data_quality:
  noise_injection:
    missing_data_rate: 0.02 # 2%の欠損値
    outlier_rate: 0.01 # 1%の異常値
    duplicate_rate: 0.005 # 0.5%の重複データ

  # リアリティを高める設定
  realistic_patterns:
    enable_customer_loyalty: true # 常連客パターン
    enable_seasonal_menu_changes: true # 季節メニュー変更
    enable_price_changes: true # 価格変更履歴
    enable_staff_shifts: true # スタッフシフトの影響

# 機械学習用特徴量設定
ml_features:
  # 時系列特徴量
  temporal_features:
    - hour_of_day
    - day_of_week
    - month_of_year
    - is_weekend
    - is_holiday
    - season

  # ビジネス特徴量
  business_features:
    - weather_condition
    - temperature
    - customer_count_previous_hour
    - running_average_sales
    - day_since_last_event

  # 顧客特徴量
  customer_features:
    - age_group
    - gender
    - visit_frequency
    - average_order_value
    - preferred_category
